<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Reembolsos</title>
    </head>
    <body>
<table width='50%' valign='center' align='center' style='background:rgba(255, 255, 255, 0.4) none repeat scroll 0% 0%; color:#00264d'>
	<tr>
		<td style='background:#7ac36f;color: #ffffff;padding: 4px;text-align: center;font-size: 18px;text-transform: uppercase;border-radius: 10px 10px;'>¡REEMBOLSO SOLICITADO!</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td style='font-family:Tahoma, Geneva, sans-serif; text-transform:uppercase;font-size:12px;' align='center'>
			Este reembolso fue solicitado el <?=$fproceso?> a las <?=$hora?>.
		</td>
	</tr>	
	<tr>
		<td style='font-family:Tahoma, Geneva, sans-serif; text-transform:uppercase;font-size:12px;' align='center'>
			<strong>Para cualquier duda o aclaración, favor de comunicarse a <span style='font-family: Courier New', Courier, monospace;'>reembolsos@megatravel.com.mx</span></strong>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>	
</table>
  </body>
</html>