<div class="row">
					<div class="col-md-12">
						<h5 class="textr">Para cualquier duda o aclaración, favor de comunicarse a: reembolsos@megatravel.com.mx</h5>
						
					</div>
					<div class="col-md-10 col-md-offset-2 " align="center">
						<h5>Bienvenido</h5>
						
					</div>
				</div>
<form name='forma' id='forma' method='post' action='controllers/solicitud_controller.php'  enctype='multipart/form-data' >
<h1 align='center'>DATOS FISCALES</h1>
<br><br>
<span style='background: #A31100; font-size:14px; color: #FFF;text-shadow: #081E82 1px 1px;border-radius: 7px 5px 5px 7px;padding: 3px 5px;'>
	Su registro no cuenta con datos fiscales cargados, para continuar con la solicitud debe llenar el siguiente formulario y adjuntar su cédula fiscal en formato PDF.
</span>
<br><br>
<div class="row">
	<div class="col-md-6">
		<table class="table">
			<tr>
				<td>RAZÓN FISCAL:</td>
				<td><input type='text' autocomplete='off' name='vrazon' required style='width:300px'></td>
			</tr>
			<tr>
				<td>DOMICILIO:</td>
				<td><input type='text autocomplete='off' ' name='vdomicilio' required style='width:300px'></td>
			</tr>
			<tr>
				<td>COLONIA:</td>
				<td>
					<input type='text' autocomplete='off'  name='vcolonia'  required style='width:300px'>
				</td>
			</tr>
			<tr>
				<td>ESTADO:</td>
				<td>
					<select  id='cestado' name='cestado'> 
						<option value="0">Seleccionar Estado</option>
						<?php foreach($estados as $estado=>$estados) {
							$estados= $estados['estado'];
							?>
								<option value="<?=$estados?>"><?=$estados?></option>
							<?php
							}

							?>
					</select>
			
				</td>
			</tr>
			<tr>
				<td>CÉDULA FISCAL:</td>
				<td><input type='file' name='archivo[]' id='archivo[]' required title='Ingresar unicamente archivo PDF'></td>
			</tr>
			<tr>
				<td>OBSERVACIONES:</td>
				<td colspan='2' rowspan='5'>
					<textarea class="form-control" name="Observaciones" rows="2" id="comment"><?=$observaciones?></textarea>
				</td>
			</tr>
			
			
		</table>
	</div>
	<div class="col-md-6">
			<table class="table">
			<tr>
				<td>RFC:</td>
				<td>
				<input type='text' autocomplete='off'  name='rfc' style='width:150px' required minlength='12' maxlength='13' pattern='^[a-zA-Z]{3,4}[\d]{6}[\D|\d]{3}?$' title='Ingrese el RFC con Homoclave (XXXX######XXX)' ></td>
			</tr>
			<tr>
				<td>C.P:</td>
				<td>
					<input type='text' autocomplete='off'  name='vcp' required style='width:150px' minlength='5' pattern='.{5,}' maxlength='5'  onKeyPress='soloNumeros()'>
				</td>
			</tr>
			<tr>
				<td>TELÉFONO:</td>
				<td>
					<input type='text'  autocomplete='off' name='vtelefono' required style='width:150px' onKeyPress='soloNumeros()'>
				</td>
			</tr>
			<tr>
				<td>MUNICIPIO:</td>
				<td>
					<select name='cmunicipio' id='cmunicipio' >
						<?=$html?>
					</select>
				</td>
			</tr>
			
		</table>
	</div>
</div>
<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6">
				<div id='aceptaD' class="divcolor1" ><input  name='validado' id='validado' type='checkbox' onchange='cambiaClase()' required title='Debe aceptar las políticas para continuar' ><label for='validado' style='cursor:pointer;'><strong>Acepto que los datos ingresados son correctos y verídicos</strong></label>
				</div>
			</div>
			
</div>
<br>
		<div class="row">
			<div class="col-md-5"></div>
			<div class="col-md-4">
				<td colspan='4' align='center'><input type='submit' value='ENVIAR' title='ENVIAR DATOS FISCALES' name='action' id='action'></td>
			</div>
		</div>
		
							<input type='hidden' name='expediente' value='<?=$expediente?>'>
							<input type='hidden' name='folio' value='<?=$id_rmbo?>'>
							<input type='hidden' name='nconsolidado' value='<?=$nconsolidado?>'>
							<input type='hidden' name='tipo' value='<?=$tipo?>'>
							<input type='hidden' name='tcliente' value='<?=$tcliente?>'>
							<input type='hidden' name='cid_cliente' value='<?=$cid_cliente?>'>		
			

</form>
<script type="text/javascript">
	$(document).ready(function(){
				$("#cestado").change(function () {
					$("#cestado option:selected").each(function () {
						edo = $(this).val();
						$.post("funciones/municipios.php", { edo: edo }, function(data){
							$("#cmunicipio").html(data);
						});            
					});
				})
			});
</script>