<!doctype html>
<html>
	<head>
		<meta http-equiv="cache-control" content="no-cache" />
		<meta http-equiv="pragma" content="no-cache" />
		<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="cssreembolsos/estilo.css">
		<link rel="stylesheet" type="text/css" href="../cssreembolsos/estilo.css">
		<title>Solicitud de Reembolsos</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
		<script src="jsf/funciones.js"></script>
		<script src="../jsf/funciones.js"></script>
<script type="text/javascript">
	
			function cambiaClase(){
				//alert('lol');
				if(document.getElementById('validado').checked==true){
					//alert('im here');
						document.getElementById('aceptaD').className = 'divcolor2';
				}
				else{
					//alert('and here too');
					document.getElementById('aceptaD').className = 'divcolor1';
				}
			}
</script>
<script type="text/javascript">
				function confirma(){
					var tcliente =$("#tcliente").val();
					if (tcliente=='A'){
						alert("¡ATENCIÓN!\n La solicitud de su reembolso debe ser impresa en hoja membretada de la agencia que lo solicita.") 
					}else if(tcliente =='D'){
						alert("¡ATENCIÓN!\n La solicitud de su reembolso debe ser impresa en hoja blanca.") 
					}
					
						
					
				}
	</script>
<script>
function valida(e){
    tecla = (document.all) ? e.keyCode : e.which;

    //Tecla de retroceso para borrar, siempre la permite
    if (tecla==8){
        return true;
    }
        
    // Patron de entrada, en este caso solo acepta numeros
    patron =/[0-9]/;
    tecla_final = String.fromCharCode(tecla);
    return patron.test(tecla_final);
}
</script>
		

	</head>
	<body onLoad="cambiaClase()">
		<header>
			<div class="container">
				<div class="navbar-header fondonav">
					
					<div class="col-md-4">
						<img src="http://lax.megatravel.com.mx/expo/img/logo_mt.png" width="100">
					</div>
					
				</div>
			</div>
			<!--<span class="logo">
			<img alt="logo" src="https://<?php echo $_SERVER['SERVER_NAME']?>/img/logo-mega-travel-blue.jpg" align="left" />
		</span>


		<?php 
			//include($_SERVER['DOCUMENT_ROOT'].'/php/cifraget.php');	
			//include($_SERVER['DOCUMENT_ROOT'].'/php/fecha.php'); 
		?>-->

		</header>
		

		<section>
			<div class="container fondodiv">
				