<?
	?>
<div class="row">
					<div class="col-md-12 textr">
						<h5 class="textr">Para cualquier duda o aclaración, favor de comunicarse a: reembolsos@megatravel.com.mx</h5>
						
					</div>
					<div class="col-md-10 col-md-offset-2 " align="center">
						<h5>Bienvenido</h5>
						
					</div>
				</div>

	<h5>Su solicitud de reembolso está incompleta, por favor termine el proceso.</h5>
	<form method='post' name='forma' id='forma' action='controllers/solicitud_controller.php' onSubmit='info(<?=$tcliente?>)'>
		
		<div class="row">
			<div class="col-md-4"></div>
			<input type='hidden' name='expediente' value='<?=$expediente?>'>
						<input type='hidden' name='nconsolidado' value='<?=$nconsolidado?>'>
			<div class="col-md-2">
				<input type='submit' title='CORREGIR DATOS' value='Corregir Datos' id='action' name='action' class="btn btn-outline-primary">
			</div>
			<div class="col-md-2">
				<td colspan='4' align='center'><input type='submit' value='Subir Carta' id='action' name='action' class="btn btn-outline-primary"></td>
			</div>
		</div>
		
		</form>
		<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </body>
</html>