<table width='60%' align='center' style='background:rgba(255, 255, 255, 0.4) none repeat scroll 0% 0%; color:#00264d'>
	<tr>
		<td style='background: rgb(0, 85, 128);color: #ffffff;padding: 4px;text-align: center;font-size: 18px;text-transform: uppercase;border-radius: 10px 10px;'>SOLICITUD DE REEMBOLSO COMPLETADA</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td height='44' style='font-family:Verdana, Geneva, sans-serif; text-transform:uppercase;font-size:16px;'><?=$cliente?></td>
	</tr>
	<tr>
		<td height='41' style='font-family:Verdana, Geneva, sans-serif; text-transform:uppercase;font-size:12px;'>Gracias por hacer uso de los servicios digitales que <span  style='font: small-caps 125%/100% serif;'> Mega Travel Operadora, S.A. de C.V.</span> pone a su disposición.
		</td>
	</tr>
	<tr>
		<td style='font-family:Tahoma, Geneva, sans-serif; text-transform:uppercase;font-size:12px;'>
			Se le ha enviado un correo de confirmación al siguiente correo electrónico <strong><?=$mail?></strong>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>	
	<tr>
		<td  align='left' style='font-family:Verdana, Geneva, sans-serif; font-size:14px'>Para cualquier aclaración, duda o sugerencia favor de comunicarse al siguiente mail:&nbsp;<span style='font-family: Courier New; font-size:16px; font-weight:bolder; text-transform:uppercase;'>reembolsos@megatravel.com.mx</span>
		</td>
	</tr>			
	<tr>
		<td  height='44'>&nbsp;</td>
	</tr>
</table>